package com.fasheng.service.model;

public class ProvinceDO extends BaseDO<Integer>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.id
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_name
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    private String provinceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.id
     *
     * @return the value of province.id
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.id
     *
     * @param id the value for province.id
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_name
     *
     * @return the value of province.province_name
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_name
     *
     * @param provinceName the value for province.province_name
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }
}