package com.fasheng.service.model;

import java.util.Date;

public class UserRegionConcernDO extends BaseDO<Integer>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.region_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String regionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.region_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.min_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double minLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.min_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double minLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.max_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double maxLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.max_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double maxLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_region_conern.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.id
     *
     * @return the value of user_region_conern.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.id
     *
     * @param id the value for user_region_conern.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.user_id
     *
     * @return the value of user_region_conern.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.user_id
     *
     * @param userId the value for user_region_conern.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.region_type
     *
     * @return the value of user_region_conern.region_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getRegionType() {
        return regionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.region_type
     *
     * @param regionType the value for user_region_conern.region_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setRegionType(String regionType) {
        this.regionType = regionType == null ? null : regionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.region_id
     *
     * @return the value of user_region_conern.region_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.region_id
     *
     * @param regionId the value for user_region_conern.region_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.min_longitude
     *
     * @return the value of user_region_conern.min_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMinLongitude() {
        return minLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.min_longitude
     *
     * @param minLongitude the value for user_region_conern.min_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMinLongitude(Double minLongitude) {
        this.minLongitude = minLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.min_latitude
     *
     * @return the value of user_region_conern.min_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMinLatitude() {
        return minLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.min_latitude
     *
     * @param minLatitude the value for user_region_conern.min_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMinLatitude(Double minLatitude) {
        this.minLatitude = minLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.max_longitude
     *
     * @return the value of user_region_conern.max_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMaxLongitude() {
        return maxLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.max_longitude
     *
     * @param maxLongitude the value for user_region_conern.max_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMaxLongitude(Double maxLongitude) {
        this.maxLongitude = maxLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.max_latitude
     *
     * @return the value of user_region_conern.max_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMaxLatitude() {
        return maxLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.max_latitude
     *
     * @param maxLatitude the value for user_region_conern.max_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMaxLatitude(Double maxLatitude) {
        this.maxLatitude = maxLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.gmt_create
     *
     * @return the value of user_region_conern.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.gmt_create
     *
     * @param gmtCreate the value for user_region_conern.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_region_conern.gmt_update
     *
     * @return the value of user_region_conern.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_region_conern.gmt_update
     *
     * @param gmtUpdate the value for user_region_conern.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}