package com.fasheng.service.dao;

import com.fasheng.service.model.EvaluationDO;

public interface EvaluationDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insert(EvaluationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    EvaluationDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKey(EvaluationDO record);
}