package com.fasheng.service.dao;

import com.fasheng.service.model.UserRegionConcernDO;

public interface UserRegionConcernDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_region_conern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_region_conern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insert(UserRegionConcernDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_region_conern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    UserRegionConcernDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_region_conern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKey(UserRegionConcernDO record);
}