package com.fasheng.service.dao;

import com.fasheng.service.model.UserDO;

public interface UserDAO {
    /**
     * 获取当前userId， 类似于oracle的sequence
     * @return
     */
    int selectCurrentUserId();
    
    /**
     * 获取下一个userId， 类似于oracle的sequence
     * @return
     */
    int selectNextUserId();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKey(UserDO record);
}