package com.fasheng.dao;

import com.fasheng.model.MessageDO;

public interface MessageDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insert(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insertSelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    MessageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKeySelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKey(MessageDO record);
}