package com.fasheng.dao;

import com.fasheng.model.MsgCatogeryDO;

public interface MsgCatogeryDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_catogery
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_catogery
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insert(MsgCatogeryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_catogery
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insertSelective(MsgCatogeryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_catogery
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    MsgCatogeryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_catogery
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKeySelective(MsgCatogeryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_catogery
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKey(MsgCatogeryDO record);
}