package com.fasheng.dao;

import com.fasheng.model.UserCatogeryConcernDO;

public interface UserCatogeryConcernDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_catogery_concern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_catogery_concern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insert(UserCatogeryConcernDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_catogery_concern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insertSelective(UserCatogeryConcernDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_catogery_concern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    UserCatogeryConcernDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_catogery_concern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKeySelective(UserCatogeryConcernDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_catogery_concern
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKey(UserCatogeryConcernDO record);
}