package com.fasheng.model;

import java.util.Date;

public class MessageDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_display_name
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String userDisplayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.image
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_catogery_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Integer msgCatogeryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_catogery_name
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String msgCatogeryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Integer msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.parent_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.attach_file
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String attachFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_expired
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Byte isExpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.deleted_status
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Byte deletedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.expire_date
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Date expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.region_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String regionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.region_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.min_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double minLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.min_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double minLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.max_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double maxLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.max_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Double maxLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_id
     *
     * @return the value of message.msg_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_id
     *
     * @param msgId the value for message.msg_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_id
     *
     * @return the value of message.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_id
     *
     * @param userId the value for message.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_display_name
     *
     * @return the value of message.user_display_name
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getUserDisplayName() {
        return userDisplayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_display_name
     *
     * @param userDisplayName the value for message.user_display_name
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setUserDisplayName(String userDisplayName) {
        this.userDisplayName = userDisplayName == null ? null : userDisplayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.image
     *
     * @return the value of message.image
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.image
     *
     * @param image the value for message.image
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_catogery_id
     *
     * @return the value of message.msg_catogery_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Integer getMsgCatogeryId() {
        return msgCatogeryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_catogery_id
     *
     * @param msgCatogeryId the value for message.msg_catogery_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMsgCatogeryId(Integer msgCatogeryId) {
        this.msgCatogeryId = msgCatogeryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_catogery_name
     *
     * @return the value of message.msg_catogery_name
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getMsgCatogeryName() {
        return msgCatogeryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_catogery_name
     *
     * @param msgCatogeryName the value for message.msg_catogery_name
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMsgCatogeryName(String msgCatogeryName) {
        this.msgCatogeryName = msgCatogeryName == null ? null : msgCatogeryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_type
     *
     * @return the value of message.msg_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_type
     *
     * @param msgType the value for message.msg_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.parent_id
     *
     * @return the value of message.parent_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.parent_id
     *
     * @param parentId the value for message.parent_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.attach_file
     *
     * @return the value of message.attach_file
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getAttachFile() {
        return attachFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.attach_file
     *
     * @param attachFile the value for message.attach_file
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setAttachFile(String attachFile) {
        this.attachFile = attachFile == null ? null : attachFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_expired
     *
     * @return the value of message.is_expired
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Byte getIsExpired() {
        return isExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_expired
     *
     * @param isExpired the value for message.is_expired
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setIsExpired(Byte isExpired) {
        this.isExpired = isExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.deleted_status
     *
     * @return the value of message.deleted_status
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Byte getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.deleted_status
     *
     * @param deletedStatus the value for message.deleted_status
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setDeletedStatus(Byte deletedStatus) {
        this.deletedStatus = deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.expire_date
     *
     * @return the value of message.expire_date
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.expire_date
     *
     * @param expireDate the value for message.expire_date
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.region_type
     *
     * @return the value of message.region_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getRegionType() {
        return regionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.region_type
     *
     * @param regionType the value for message.region_type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setRegionType(String regionType) {
        this.regionType = regionType == null ? null : regionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.region_id
     *
     * @return the value of message.region_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.region_id
     *
     * @param regionId the value for message.region_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.min_longitude
     *
     * @return the value of message.min_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMinLongitude() {
        return minLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.min_longitude
     *
     * @param minLongitude the value for message.min_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMinLongitude(Double minLongitude) {
        this.minLongitude = minLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.min_latitude
     *
     * @return the value of message.min_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMinLatitude() {
        return minLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.min_latitude
     *
     * @param minLatitude the value for message.min_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMinLatitude(Double minLatitude) {
        this.minLatitude = minLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.max_longitude
     *
     * @return the value of message.max_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMaxLongitude() {
        return maxLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.max_longitude
     *
     * @param maxLongitude the value for message.max_longitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMaxLongitude(Double maxLongitude) {
        this.maxLongitude = maxLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.max_latitude
     *
     * @return the value of message.max_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Double getMaxLatitude() {
        return maxLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.max_latitude
     *
     * @param maxLatitude the value for message.max_latitude
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setMaxLatitude(Double maxLatitude) {
        this.maxLatitude = maxLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_create
     *
     * @return the value of message.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_create
     *
     * @param gmtCreate the value for message.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_update
     *
     * @return the value of message.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_update
     *
     * @param gmtUpdate the value for message.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}