package com.fasheng.model;

import java.util.Date;

public class PartnerUserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.partner_user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String partnerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.partner_detail
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String partnerDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.version
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.access_token
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.refresh_token
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_user.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.id
     *
     * @return the value of partner_user.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.id
     *
     * @param id the value for partner_user.id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.type
     *
     * @return the value of partner_user.type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.type
     *
     * @param type the value for partner_user.type
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.user_id
     *
     * @return the value of partner_user.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.user_id
     *
     * @param userId the value for partner_user.user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.partner_user_id
     *
     * @return the value of partner_user.partner_user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getPartnerUserId() {
        return partnerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.partner_user_id
     *
     * @param partnerUserId the value for partner_user.partner_user_id
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setPartnerUserId(String partnerUserId) {
        this.partnerUserId = partnerUserId == null ? null : partnerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.partner_detail
     *
     * @return the value of partner_user.partner_detail
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getPartnerDetail() {
        return partnerDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.partner_detail
     *
     * @param partnerDetail the value for partner_user.partner_detail
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setPartnerDetail(String partnerDetail) {
        this.partnerDetail = partnerDetail == null ? null : partnerDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.version
     *
     * @return the value of partner_user.version
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.version
     *
     * @param version the value for partner_user.version
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.access_token
     *
     * @return the value of partner_user.access_token
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.access_token
     *
     * @param accessToken the value for partner_user.access_token
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.refresh_token
     *
     * @return the value of partner_user.refresh_token
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.refresh_token
     *
     * @param refreshToken the value for partner_user.refresh_token
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.gmt_create
     *
     * @return the value of partner_user.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.gmt_create
     *
     * @param gmtCreate the value for partner_user.gmt_create
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_user.gmt_update
     *
     * @return the value of partner_user.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_user.gmt_update
     *
     * @param gmtUpdate the value for partner_user.gmt_update
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}