package com.fasheng.dao;

import java.util.List;

import com.fasheng.model.DistrictDO;

public interface DistrictDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int insert(DistrictDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    DistrictDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Dec 06 23:15:11 CST 2011
     */
    int updateByPrimaryKey(DistrictDO record);
    
    /**
     * get all districts
     * @return
     */
    List<DistrictDO> selectAllDistricts();
    
    List<Integer> selectDistrictIdsByCityId(Integer cityId);
}