package com.fasheng.dao;

import java.util.List;

import com.fasheng.model.ProvinceDO;

public interface ProvinceDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    int insert(ProvinceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    ProvinceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Tue Dec 06 23:49:50 CST 2011
     */
    int updateByPrimaryKey(ProvinceDO record);
    
    /**
     * get all provinces
     * @return
     */
    List<ProvinceDO> selectAllProvinces();
}